spring.datasource.url=jdbc:postgresql://localhost:5433/ledger
spring.datasource.username=postgres
spring.datasource.password=mysecretpassword
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=MySuperSecretKeyForJwtSigning12345
jwt.expiration=86400000
twilio.accountSid=AC0a1836f566272cdd2ea46a8c9b1d1e67
twilio.authToken=36310a2ae2be8a01fd4119ec5e9460da
twilio.fromNumber=+14149282205
